version: "3.1"

services:
  php:
    container_name: mawaqit_php
    build: docker/php-fpm
    restart: always
    environment:
      APP_ENV: prod
      COMPOSER_HOME: /application/docker/data/composer
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro

  nginx:
    container_name: mawaqit_nginx
    image: nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/prod.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 80:80
      - 443:443

  db:
    container_name: mawaqit_mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /var/www/mawaqit/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env