version: "3.1"

services:
  php-fpm:
    build: docker/php-fpm
    restart: always
    tty: true
    environment:
      APP_ENV: pp
    links:
      - mysql
      - maildev
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh

  nginx:
    image: nginx:alpine
    restart: always
    working_dir: /application
    links:
      - php-fpm
    volumes:
      - .:/application
      - ./docker/nginx/pp.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
      - 443:443

  mysql:
    image: mysql:5.6
    restart: always
    volumes:
      - /var/www/mawaqit/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: mawaqit
      MYSQL_DATABASE: mawaqit

  composer:
    image: composer:1.9.0
    volumes:
      - ./:/app
    command: install -o -n --no-dev

  maildev:
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 81:80