version: "3.1"

services:
  mawaqit_php:
    container_name: mawaqit_php
    build: docker/php-fpm
    restart: always
    environment:
      APP_ENV: dev
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh
      # clock
      - /etc/localtime:/etc/localtime:ro

  mawaqit_nginx:
    container_name: mawaqit_nginx
    image: nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
      # clock
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 10001:80

  mawaqit_mysql:
    container_name: mawaqit_mysql
    image: mysql:5.6
    restart: always
    volumes:
      # clock
      - /etc/localtime:/etc/localtime:ro
    environment:
      MYSQL_ROOT_PASSWORD: mawaqit
      MYSQL_DATABASE: mawaqit
    ports:
      - 10002:3306

  mawaqit_composer:
    image: composer:1.9.0
    volumes:
      - ./:/app
    command: install -n

  mawaqit_maildev:
    container_name: mawaqit_maildev
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 10003:80