version: '3'

services:
  mawaqit:
    container_name : mawaqit
    restart: always
    build: .
    tty: true
    links:
      - db:mysql
    ports:
      - 80:80
      - 443:443
    volumes:
      # symfony code
      - ./:/var/www/mawaqit
      # nginx / php
      - ./docker/config/php/php.ini:/etc/php/7.3/fpm/conf.d/mawaqit_custom.ini
      - ./docker/config/php/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/pp.prod.conf:/etc/nginx/sites-enabled/default
      - ./docker/data/logs/nginx:/var/log/nginx
      # ssh
      - ~/.ssh:/root/.ssh
      # clock
      - /etc/localtime:/etc/localtime:ro
    command: >
      sh -c "while true; do nginx -s reload; sleep 12h; done;"

  db:
    image: mysql:5.6
    container_name : db
    restart: always
    volumes:
      - /var/www/mawaqit/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: mawaqit
      MYSQL_ROOT_PASSWORD: mawaqit
