version: "3.1"

services:
  mawaqit_php:
    container_name: mawaqit_php
    build: docker/php-fpm
    restart: always
    environment:
      APP_ENV: pp
      COMPOSER_HOME: /application/docker/data/composer
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh
      - /etc/localtime:/etc/localtime:ro

  mawaqit_nginx:
    container_name: mawaqit_nginx
    image: nginx:alpine
    restart: always
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/nginx/pp.conf:/etc/nginx/conf.d/default.conf
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/data/logs/nginx:/var/log/nginx
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:80

  mawaqit_mysql:
    container_name: mawaqit_mysql
    image: mysql:5.6
    restart: always
    volumes:
      - /var/www/mawaqit/mysql:/var/lib/mysql
      - /etc/localtime:/etc/localtime:ro
    env_file:
      - .env

  mawaqit_maildev:
    container_name: mawaqit_maildev
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 82:80