version: '3'

services:
  mawaqit:
    build: .
    container_name: mawaqit
    restart: always
    tty: true
    links:
      - mawaqit_db
      - mawaqit_maildev
    ports:
      - 80:80
    volumes:
      # symfony code
      - ./:/var/www/mawaqit
      # nginx / php
      - ./docker/config/php/php.ini:/etc/php/7.3/fpm/conf.d/mawaqit_custom.ini
      - ./docker/config/php/www.conf:/etc/php/7.3/fpm/pool.d/www.conf
      - ./docker/config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/config/nginx/mawaqit.localhost.conf:/etc/nginx/sites-enabled/default
      - ./docker/data/logs/nginx:/var/log/nginx
      # ssh
      - ~/.ssh:/root/.ssh
      # clock
      - /etc/localtime:/etc/localtime:ro

  mawaqit_db:
    container_name: mawaqit_db
    restart: always
    image: mysql:5.6
    expose:
      - 1106
    ports:
      - 1106:3306
    environment:
      MYSQL_DATABASE: mawaqit
      MYSQL_ROOT_PASSWORD: mawaqit

  mawaqit_maildev:
    container_name: mawaqit_maildev
    restart: always
    image: djfarrelly/maildev:latest
    expose:
      - 1080
    ports:
      - 1080:80