version: "3.1"

services:
  php-fpm:
    build: docker/php-fpm
    restart: always
    tty: true
    environment:
      APP_ENV: dev
    links:
      - mysql
      - maildev
    working_dir: /application
    volumes:
      - .:/application
      - ./docker/php-fpm/php-ini-overrides.ini:/etc/php/7.3/fpm/conf.d/99-overrides.ini
      - ~/.ssh:/root/.ssh

  nginx:
    image: nginx:alpine
    restart: always
    working_dir: /application
    links:
      - php-fpm
    volumes:
      - .:/application
      - ./docker/nginx/dev.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8101:80
      - 80:80

  mysql:
    image: mysql:5.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: mawaqit
      MYSQL_DATABASE: mawaqit

    ports:
      - 8102:3306

  composer:
    image: composer:1.9.0
    volumes:
      - ./:/app
    command: install -n

  maildev:
    restart: always
    image: djfarrelly/maildev:1.1.0
    ports:
      - 8103:80