parameters:
    locale: 'fr'
    name: 'Mawaqit'
    site: 'https://mawaqit.net'
    languages: [ar, fr, en, tr, de, nl, it, es, hr, ta, sq, pt]
    no_reply_address: 'no-reply@mawaqit.net'
    google_api_endpoint: 'https://maps.googleapis.com/maps/api'
    weather_api_endpoint: 'http://api.openweathermap.org/data/2.5/weather'
    slack_bot: 'Monolog Prod'
    slack_channel: '#prod-errors'
    api_base_url: '%site%'
    app_apple_store_url: 'https://itunes.apple.com/fr/app/mawaqit/id1460522683'
    app_google_play_url: 'https://play.google.com/store/apps/details?id=com.kanout.mawaqit'