parameters:
    locale: fr
    name: Mawaqit
    languages: [ar, fr, en, tr, de, nl, it, es, hr, ta, sq, pt]
    mailer_transport: smtp
    mailer_host: SSL0.OVH.NET
    mailer_port: 587
    mailer_user: '%supportEmail%'
    no_reply_address: no-reply@mawaqit.net
    postmaster_address: postmaster@mawaqit.net
    supportTelFR: '0033651061498 / 0033629111641'
    supportTelDZ: '00213551720574 / 00213550282964'
    supportTelROW: '0033638159980'
    supportEmail: contact@mawaqit.net
    google_api_endpoint: 'https://maps.googleapis.com/maps/api'
    weather_api_endpoint: 'http://api.openweathermap.org/data/2.5/weather'
    slack_bot: 'Monolog Prod'
    slack_channel: '#prod-errors'
    site: 'https://mawaqit.net'
    api_base_url: '%site%'
    app_apple_store_url: https://itunes.apple.com/fr/app/mawaqit/id1460522683
    app_google_play_url: https://play.google.com/store/apps/details?id=com.kanout.mawaqit