imports:
  - { resource: config_prod.yml }

#swiftmailer:
#    default_mailer: memory
#    mailers:
#        memory:
#            host: mawaqit_maildev
#            port: 25
#        file:
#            host: mawaqit_maildev
#            port: 25