imports:
  - { resource: config.yml }

framework:
  assets:
    version: %version%

swiftmailer:
  disable_delivery: true

monolog:
  handlers:
    main:
      type:         fingers_crossed
      action_level: error
      handler:      nested
      excluded_404s:
        - ^/
    nested:
      type:  rotating_file
      path: '%kernel.logs_dir%/%kernel.environment%.log'
      level: error
      max_files: 1