imports:
  - { resource: config.yml }

framework:
  router:
    resource: '%kernel.root_dir%/config/routing_dev.yml'
    strict_requirements: true
  profiler: { only_exceptions: false }

web_profiler:
  toolbar: true
  intercept_redirects: false

monolog:
  handlers:
    main:
      type: fingers_crossed
      action_level: error
      max_files: 1
      channels: [!event, !php, !security]
      handler: stream
    stream:
      type: stream
      path: "%kernel.logs_dir%/%kernel.environment%.log"

hautelook_alice:
  fixtures_path: 'Resources/fixtures/orm'

swiftmailer:
    default_mailer: memory
    mailers:
        memory:
            host: mawaqit_maildev
            port: 25
        file:
            host: mawaqit_maildev
            port: 25