app:
    resource: '@AppBundle/Controller/'
    type: annotation
    
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
    prefix: /backoffice

easy_admin_bundle:
    resource: "@EasyAdminBundle/Controller/AdminController.php"
    type:     annotation
    prefix:   /backoffice/admin

_liip_imagine:
    resource: "@LiipImagineBundle/Resources/config/routing.yaml"
    options:
      i18n: false
