imports:
    - { resource: "services_legacy.yml" }

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    AppBundle\Controller\:
        resource: '../../src/AppBundle/Controller'
        tags: ['controller.service_arguments']

    AppBundle\EventListener\CommentListener:
        arguments:
            - "@security.token_storage"
        tags:
            - { name: doctrine.event_listener, event: prePersist }

    AppBundle\EventListener\MosqueElasticListener:
        arguments:
            - "@app.mosque_service"
            - "@doctrine.orm.entity_manager"
            - "@app.request_service"
        tags:
            - { name: 'doctrine.event_subscriber' }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }