AppBundle\Entity\Comment:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        text:
            type: text
        createdAt:
            type: datetime

    manyToOne:
        user:
            targetEntity: AppBundle\Entity\User
            joinColumn:
                nullable: false
                onDelete: CASCADE
        mosque:
            targetEntity: AppBundle\Entity\Mosque
            inversedBy: comments
            joinColumn:
                nullable: false
                onDelete: CASCADE
