AppBundle\Entity\Parameters:
    type: entity
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        key:
            column: key_param
            type: string
            unique: true
        value:
            column: value_param
            type: string
        comment:
            type: string
            length: 1024
            nullable: true