easy_admin:
  site_name: Mawaqit
  design:
    menu:
      - { entity: User, label: Utilisateurs, icon: user, default: true }
      - { entity: Faq, icon: question}
      - { entity: Parameters, label: Paramètres, icon: cog}
    brand_color: '#448531'
  formats:
    date:     d/m/Y
    time:     H:i
    datetime: d/m/Y H:i