easy_admin:
  entities:
    Faq:
      class: AppBundle\Entity\Faq
      list:
        sort: ['position', 'ASC']
        actions:
          - { name: 'show', icon: 'eye', label: false }
          - { name: 'edit', icon: 'pencil', label: false }
          - { name: 'delete', icon: 'trash', label: false }
      form:
        fields:
          - question
          - { property: answer, css_class: 'tinymce'}
          - position
