easy_admin:
  entities:
    Faq:
      class: AppBundle\Entity\Faq
      list:
        sort: ['position', 'ASC']
      form:
        fields:
          - question
          - { property: answer, css_class: 'tinymce'}
          - position
