easy_admin:
  entities:
    User:
      class: AppBundle\Entity\User
      disabled_actions: [new]
      list:
        actions:
          - { name: 'show', icon: 'eye', label: false }
          - { name: 'edit', icon: 'pencil', label: false }
          - { name: 'delete', icon: 'trash', label: false }
        collapse_actions: true
        fields: [id, email, enabled, roles, mosqueQuota, apiCallNumber, apiQuota, apiUseDescription, created, lastLogin]
      form:
        fields:
          - id
          - username
          - email
          - enabled
          - { property: roles, type: choice, type_options: { multiple: true, choices: { ROLE_SUPER_ADMIN: ROLE_SUPER_ADMIN, ROLE_ADMIN: ROLE_ADMIN, ROLE_USER: ROLE_USER } } }
          - mosqueQuota
          - apiQuota
          - apiAccessToken
          - apiUseDescription